name: Run unit tests

on:
    pull_request:
        branches: ['main']

jobs:
    dotnet-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x
            - name: Test
              run: dotnet test --filter "Category=Unit" --verbosity=quiet
